apiVersion: v1
kind: Service
metadata:
  name: devops-fastapi-service
spec:
  type: NodePort
  selector:
    app: devops-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30123

